server {
    listen 80;
    listen [::]:80;

    server_name l.cnhalo.com;

    access_log /var/log/nginx/l.cnhalo.com.access.log;
    error_log /var/log/nginx/l.cnhalo.com.error.log;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name l.cnhalo.com;

    ssl_certificate /etc/letsencrypt/live/l.cnhalo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/l.cnhalo.com/privkey.pem;

    access_log /var/log/nginx/l.cnhalo.com.access.log;
    error_log /var/log/nginx/l.cnhalo.com.error.log;

    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
